### ISSUE TITLE
"hacking attempt!"

### ISSUE THREAD

**Issue by moi-001** [Piwigo/piwigo-tag-recognition#4]
Bonjour, 
J'utilise la dernière version de piwigo 12.1 et j'ai installé votre plugin  piwigo-tag-recognition et lorsque je vais sur configuration une page souvre avec le mesage " Hacking attempt! "
Merci  de m'aider

---
Hello,
I use the latest version of Piwigo 12.1 and I installed your Piwigo-Tag-Recognition plugin and when I go on configuration a page opens with the "hacking attempt!"
Thank you for helping me

**Comment by Zacharieg** [comment]
Sorry, I found the bug, it will be fixed in the new update.
